name: xss-app
services:
  app_flight_a:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${IP_ADDR_A:-127.0.0.1}:${PORT_A:-5091}:5000
  app_flight_b:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${IP_ADDR_B:-127.0.0.1}:${PORT_B:-5092}:5000
  app_flight_c:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${IP_ADDR_C:-127.0.0.1}:${PORT_C:-5093}:5000
  app_flight_d:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${IP_ADDR_D:-127.0.0.1}:${PORT_D:-5094}:5000


